### ISSUE TITLE
Move test builds to consistent location

### ISSUE THREAD

**Issue by alerque** [source-foundry/Hack#185]
I just went to create an Arch Linux package for installing test versions of Hack and discovered that the locations for these builds is so arbitrary that fetching them can't be codified. Here are some things I would recommend changing to make it easier for downstream people to test:
1. Version test builds with a string that sorts in the correct order. Instead of 03062016 it should be 20160306.
2. Place all tests builds in the same location. Right now one is in the test_builds folder, two are in subdirectories with a build number. I would place all of them in the test_builds folder. This way the same URL will always reach the font files and updating to the latest test version will be scriptable.
3. The development branch should have tags at each development build you _want_ people specifically downloading and testing. This way you can easily tweak the URL that retrieves the latest development branch to retrieve the branch at the tag point to get a specific revision. Also with these tags in place `git describe --tags` will return something that can be used to identify the last development release point.

TODO: 

- [x]  eliminate any separate directory path structure for "test" (i.e. development) builds.

**Comment by chrissimpkins** [comment]
I didn't have an intent to widely distribute these.     They are intended to investigate specific changes that occur in the fonts and are incomplete versions that are not intended for broad use.  I would be happy to prepare a 'release candidate' prior to releases and allow for evaluation and comment.  I have done this in the past and received no comments.  Do you think that this is worth the effort?

**Comment by alerque** [comment]
I guess it depends on your workflow some too, but the barrier for me is that it isn't easy to switch between versions. I'd be happy to test things out if I could do switch between versions with a single command to my package manager rather than having to go manually download multiple files, find the target locations, remove production versions, insert files, rebuild font caches, etc. In spite of my interest I haven't  tried out the italic pipe updates yet just because it's a hassle.

**Comment by chrissimpkins** [comment]
I see.  Makes sense.  I have been sloppy about the organization of these builds to date because I also remove them with each release.  We can definitely create a formal versioning approach.  Will be back in touch this week to discuss it in more detail.  If manual installs are really that much of a disincentive, perhaps what we need is an installer so that this is available to all.

**Comment by chrissimpkins** [comment]
Will modify our test build versioning approach/paths following the v2.020 release.  Hope to have this out in the next couple of weeks and then we can work out an approach.

**Comment by chrissimpkins** [comment]
@texhex @alerque 

Tex, is there a way that we can satisfy the test build directory structure for your install tool in a way that works for Caleb?  See his report above.

Thanks.

**Comment by texhex** [comment]
Disclaimer: I'm a git noob, so I don't know if I understand everything @alerque alerque and you were talking about. But I think it boils down to have a consistent URL for the development builds (regardless if its in master or dev branch). 

Then it depends if you only have one set of -DEV fonts you are working with or if there are several active at the same time? I think if you always have one set -of DEV fonts where you are adding the new stuff, there would be one set (= one URL) where the newest development version can be retrieved. 

My suggestion: Ditch the sub folders in /test-builds and upload the newest dev version directly to that folder. In case we need before/after tests later on, e.g. for Java Glyph Tester, we could use tags so (with a little scripting) it would be possible to download older versions. The URLs for the newest version would still be valid.

**Comment by chrissimpkins** [comment]
@alerque Thoughts?

**Comment by alerque** [comment]
As long as they are in the same place every time with consistent naming (preferably without a version string in the filename) it doesn't make that much of a difference for packaging. If it were mine I wouldn't commit them to the master branch just so that the entire history of blobs for every build doesn't get dragged along with every checkout. Hence I would suggest attaching them to Github release tags or perhaps throwing them in LFS.

**Comment by chrissimpkins** [comment]
We are going to eliminate the entire test build directory as of v3.0 release.  There will only be fonts released under `build` and anything that is pre-release will be designated as such in the version string.  We also intend to stamp the font version string with the git commit short sha1 string so that it is linked to a repository state at the time of build.  

Adding this to v3.0 milestone so that I make sure to eliminate the entire test build directory.

**Comment by chrissimpkins** [comment]
We will also be using a git sha1 commit hash string versioning approach within the font build version strings so that it is not necessary to isolate these physically from "release" builds.  There will just be sha1 stamped builds and we will use releases / master branch merges to define what is a release vs what is a development build.  Tools for this in place and versioning is taking place with the builds in development branches now.

**Comment by chrissimpkins** [comment]
Now in `dev` branch and will be merged to master as part of v3.0 release
