### ISSUE TITLE
More easily distinguishable capital `Q` [U+0051]

### ISSUE THREAD

**Issue by jdw1996** [source-foundry/Hack#367]
The current version of the capital `Q` has a fairly small tail, especially when the font size is set small (I use 11pt in my terminal and in Vim).  It would be nice if it were more noticeable, either by being bigger (perhaps curled under the main "body" of the letter) or by continuing inside the oval "body", something like this:
![capital Q](http://actsonline.net/wp-content/uploads/2014/05/9QTWjD1X.jpeg)

**Comment by chrissimpkins** [comment]
Have a font editor and want to give the edit a go then show us some screenshots with it?

**Comment by jdw1996** [comment]
I've used BirdFont, but I don't believe it supports UFO fonts.  Are there any you would recommend, given that I'm running Ubuntu?  TruFont seems like it might be an option.

**Comment by chrissimpkins** [comment]
TruFont and FontForge should both work on Ubuntu and will both support UFO source.  If it is something of interest to you, definitely feel free to work on a new design and show us pre/post screenshot images across sizes 8 - 14 that demonstrate the problem that you are attempting to solve with the change.  Check out the CONTRIBUTING.md document before you start committing to the UFO source because there are some important files that you will need to exclude from your commits (or just work out of repo and drop the modified *.glif files in repo when complete...).  

Look forward to seeing what you come up with so that we can decide if it is appropriate as a new default here or should be a new alternate glyph in [alt-hack](https://github.com/source-foundry/alt-hack) for custom builds.  We can definitely make the new design available in one way or the other based upon feedback that you receive.

**Comment by jdw1996** [comment]
Sounds good, thanks.  I'll let you know when I've got something.

**Comment by chrissimpkins** [comment]
Sounds great! Look forward to seeing it.

**Comment by jdw1996** [comment]
I've been playing around with shapes for the `Q`, but it's more difficult than I was thinking.  When I continue the tail into the oval, it looks too crowded, and when I make the tail larger and curvier, the `Q` ends up looking bigger than the other capital letters.  The best solution I've come up with is simply lengthening the tail.

Here's the current version, in some text:
![writer-original-q](https://user-images.githubusercontent.com/17225098/34636405-83118be0-f26e-11e7-9cea-716ab2d59154.png)

And the modified version:
![writer-modified-q](https://user-images.githubusercontent.com/17225098/34636408-8d67af5c-f26e-11e7-9cd6-0f6e3a1e01a1.png)

It's an extremely small change, but it makes a difference at the small size I use in my terminal, to my eyes:
![terminal-original-q](https://user-images.githubusercontent.com/17225098/34636418-b4ceaa14-f26e-11e7-9684-91d980fa5775.png)
vs
![terminal-modified-q](https://user-images.githubusercontent.com/17225098/34636420-baffbd1a-f26e-11e7-827c-5a27a7fc847c.png)

Let me know what you think.

**Comment by chrissimpkins** [comment]
LGTM! 

I am going to try to push 3.001 this weekend and tagged this as work for the v3.002 release.  Let's see what feedback we get on your changes here and then make a decision about adding this as part of the next release.  If you haven't done so, check out the build instructions and build a set with that change so that you can use it for a bit to confirm that you are satisfied with it. 

My own opinion is that I agree with you that this glyph warrants a change.  I like your design here.  It's subtle but does seem to make a difference.

**Comment by jdw1996** [comment]
Alright, thanks for the feedback!  One other thing: I saw that there's a Cyrillic letter "qa" that looks like a `Q` to me, but I'm not familiar with the Cyrillic alphabet... Should I make the change to it as well?

**Comment by chrissimpkins** [comment]
We will need to look through the entire set and make changes to all glyphs based on the upper case Q shape across all four sets if we add this change.

**Comment by chrissimpkins** [comment]
@jdw1996 ready to get started on this?  I should have some time over the next couple of weeks if it works for you.

**Comment by jdw1996** [comment]
Yeah, sounds great.  I've got updated versions of the glyphs in all styles, and I've been using a version of the font with the modified `Q` for the last couple weeks.  It seems to work well.

What's the best way to share the changes?  Should I make a pull request to a certain branch?

**Comment by chrissimpkins** [comment]
Sounds good!  Please have a look at the CONTRIBUTING.md docs section re: specifics of how to submit a pull request for glyph changes:

https://github.com/source-foundry/Hack/blob/master/CONTRIBUTING.md#glyph-modifications  

You can base this work on the `dev` branch.  This will be merged to master this week for the release of v3.001 and we will plan for this change to be a part of the work for v3.002.

Let me know if you have any questions.

**Comment by chrissimpkins** [comment]
These changes were merged to `dev` branch and are slated to be part of the v3.003 release.
