### ISSUE TITLE
vertically dashed zero hard to get used to

### ISSUE THREAD

**Issue by fabiangreffrath** [source-foundry/Hack#399]
Hi there,

thank you very much for the impressive effort that went into the Hack 3.00x release!

However, I find the new design of the '0' glyph with the "vertical dash" very hard to get used to. I know there are some alternative characters available in the alt-hack library, but I am usually using the fonts as provided by my Linux distro, and this in turn usually stays with the upstream defaults.

I am not asking to make up a new design for the '0' glyph, but to reconsider the choice of making the vertically dashed variant the default one and switch to e.g. a dotted version instead.

Thanks,

Fabian

**Comment by chrissimpkins** [comment]
Thanks for the note Fabian.  The zero has always been a polarizing shape in this design.  You either love it, or you don't.  It is a big part of the identity of the Hack typeface and was the very first design change that I made to the upstream Bitstream Vera Sans Mono source that began the path that is Hack.  It is not a new part of the design.  This shape has been present from the start.

It became clear to us that many users wanted to tweak shapes and swap out glyphs in select positions which were a significant factor in the licensing changes & new alternative glyph repository that came with the v3.000 release of Hack.  There are now downstream repos that maintain different lowercase `i`, different `0`, additional glyph sets, etc. combinations using the glyphs in the alt-hack repository or the downstream project's designs.  This was an intentional move on our part because we recognized that it is simply not possible to satisfy the subjective wants of all users, yet feel that there are good things in the Hack design that might be preserved in new derivatives to meet their needs.  We want Hack to be used as the base for new developments with the fantastic Bitstream Vera Sans Mono and DejaVu Sans Mono faces and I hope that part of our contribution to this tree, beyond the design changes here, is a simple approach to compile from open UFO text source files for these downstream projects so that the design lineage can continue to grow and expand to meet new needs.  I consider that a benchmark of success for an open project like ours.

All of that is to say that the default zero won't change for "Hack" because to me and many others it would not be Hack any longer, but I would be very willing to invite you to the organization account, and we can develop a derivative that swaps out the zeroes in the source for a new design in order to allow you to maintain a derivative that you like.  We manually adjust the ttfautohint automated hints for the zero glyphs and this would require a bit of investigation + adjustment for the new shapes which I would be very willing to contribute to that repository.  If you would be willing to do this, I think that you will find that there are many users out there who share your opinion and would use the design with either a dotted or slashed zero.  

Let me know if this is of any interest.  Work could begin immediately on my end.  The changes would not be difficult and we could have a set of fonts available in a day or two.  Unfortunately, I don't have the time to be the primary maintainer so this would require someone else to take point if it is to stay current with upstream Hack changes.

**Comment by chrissimpkins** [comment]
If I am not mistaken, you are using the Debian package? Is that correct?

**Comment by fabiangreffrath** [comment]
Dear @chrissimpkins , thank you very much for your detailed reply!

> If I am not mistaken, you are using the Debian package

Actually, I am one of its maintainers! When I uploaded the package last night (it has already been accepted \o/), I was curious and set it as my terminal font when I realized the zero glyph somehow looked strange to me. What I didn't realize, though, was that I was using DejaVu Sans Mono before and simply got used to its glyph shape.

So, nothing wrong here and thanks again for your friendly reply and offer to help!

**Comment by chrissimpkins** [comment]
@fabiangreffrath haha! I guess another option is to simply use Bitstream Vera Sans Mono or DejaVu Sans Mono upstreams :)  If you ever come across the time to maintain a dotted or slashed zero derivative that works better for you, let me know.  I have always wanted to do this, I just don't have the time...

> I am one of its maintainers

I thought that was the case but couldn't recall!  Sorry...  I try to keep track. Thanks for all of your help with the package Fabian.  I added a new note to our acknowledgments section to broadly all of those who package these fonts now that I recognize what it involves.  I never appreciated the amount and depth of work that you go through.  It really is very much appreciated.
