### ISSUE TITLE
Bold brackets and braces in `dev` are too low

### ISSUE THREAD

**Issue by jdw1996** [source-foundry/Hack#443]
It seems the centre-line of the square brackets and curly braces is lower in the bold weight than in the regular weight, in the version of the fonts currently in `dev`.  Here's a GIF showing the difference, made using a fresh build of the fonts from `dev`:

![hack-braces](https://user-images.githubusercontent.com/17225098/42398851-8392c94e-8139-11e8-894a-a69efd624838.gif)

I see the same thing when toggling between regular italics and bold italics.  I'm not sure if it's a design decision or if the bold glyphs just weren't moved upward at the same time as the regular ones.

**Comment by chrissimpkins** [comment]
Thanks Joseph.  Linux? Assuming that you see this across our target sizes 8-14?  

Will take a look.  I thought that I addressed all of these when we worked on the parentheses.

**Comment by jdw1996** [comment]
Hi Chris.  Yes, this is on Xubuntu Linux.  I first noticed it in code in Vim, at size 11.  I can post screenshots at a smaller size tomorrow if it will help.

**Comment by chrissimpkins** [comment]
Thanks.  No need to post images.  Just confirming.  I will take a look at the design and post here when I have more information.

**Comment by chrissimpkins** [comment]
You are correct!  There are vertical alignment issues in both bold and bold italic sets.

Regular

![hack-regular](https://user-images.githubusercontent.com/4249591/42856025-55327938-8a11-11e8-89e3-58d8daee1d06.png)

Italic

![hack-italic](https://user-images.githubusercontent.com/4249591/42856037-5d4557ee-8a11-11e8-995a-ecc222d30e09.png)


Bold

![hack-bold](https://user-images.githubusercontent.com/4249591/42856044-67d8353c-8a11-11e8-871e-df4e4c2175be.png)


Bold Italic

![hack-bolditalic](https://user-images.githubusercontent.com/4249591/42856051-6dfab23c-8a11-11e8-8035-f7eeafae0f11.png)

Thanks for checking this Joseph.  Will make the changes so that they are aligned...

**Comment by chrissimpkins** [comment]
This should be fixed as of https://github.com/source-foundry/Hack/pull/444/commits/c1f45d1898bde61f7bb09d0b377cc6d996210d5a in https://github.com/source-foundry/Hack/pull/444 

Want to build and confirm that you are seeing a fix on your platform?

**Comment by jdw1996** [comment]
Hey Chris, I just rebuilt with the glyphs from the PR and it solved the issue.  Thanks!

**Comment by chrissimpkins** [comment]
Excellent! Thanks for reporting this.  I will merge it into dev.  Have been a bit tied up with other things but am anxious to get this release out soon.  Thanks again for all of the work that you contributed for 4.000.  Things are looking good!

**Comment by chrissimpkins** [comment]
merged to dev for release as part of v4.000 release work
