### ISSUE TITLE
Build not reproduceable

### ISSUE THREAD

**Issue by copart** [source-foundry/Hack#481]
Hi,

Trying to build the fonts. I tried both master and dev branch.

python3 -m venv venv
venv/bin/python3 -m pip install fontmake
venv/bin/python3 -m pip install fonttools
venv/bin/python3 -m pip install fs
venv/bin/python3 -m pip install ttfautohint-py

I then build, fontmake and fontbakery works.

**However, in post processing**:
venv/bin/python3 -m ttfautohint -l 6 -r 50 -x 10 -H 181 -D latn -f latn -w G -W -t -X "" -I -m postbuild_processing/tt-hinting/Hack-Regular-TA.txt master_ttf/Hack-Regular.ttf master_ttf/hinted/Hack-Regular.ttf 
venv/lib64/python3.7/site-packages/ttfautohint/options.py:455: UserWarning: Option '-w' is deprecated! Use option '-a' instead
  UserWarning("Option '-w' is deprecated! Use option '-a' instead"))
**ttfautohint: ERROR: postbuild_processing/tt-hinting/Hack-Regular-TA.txt:3:1: invalid glyph name (0x204)
  uni0023 touch 0,1,2,3,18,19,20,21,22,23,24,25,26,27,28,31 x 0.25  @ 13**

Any ideas?

**Comment by habamax** [comment]
I have the same error -- wanted to build slashed zero variant -- started with default font first.

And I have exactly the same error.

I do it on windows WSL opensuse leap 15.

**Comment by chrissimpkins** [comment]
Sorry.  I have to update all of the documentation in the dev branch. I apologize for all of the troubles.  I think that this may be related to how newer versions of the compiler (fontmake) treats the glyph names.  We are named with production names in the ttfautohint scripts and I don't think that those are generated by default with the compiler any longer.  All versions of the build tools are pinned using pipenv in the dev branch. 

Give this a try:


Install `pipenv` globally:

```
$ pip install pipenv
```

Navigate to the Hack source that you cloned and use the make file target that builds all dependencies.  This takes a bit of time because it compiles local pinned version installs of Harfbuzz, Freetype and ttfautohint, then builds all of the fonts (including web fonts + subsets).  

```
$ make build-with-dependencies
```

After you make those upstream default fonts, you can just use the make target for the build that you want after you modify the source with alternates.  For ttf builds only, 

```
$ make ttf
```

Let me know if that is still a problem.

**Comment by habamax** [comment]
`make build-with-dependencies` 

![image](https://user-images.githubusercontent.com/234774/54494614-44c94180-48ed-11e9-95ae-85b554536639.png)

**Comment by habamax** [comment]
Not sure if the following error matters?

![image](https://user-images.githubusercontent.com/234774/54494644-a093ca80-48ed-11e9-9fe7-ec40b99c58d5.png)

I do non-sudo make, should I do it with more privilegies?

**Comment by habamax** [comment]
`sudo make build-with-dependencies` has the same error as OP.

**Comment by copart** [comment]
can we use pip to request a specific version of fontmake?  perhaps the version that you know worked. I am not too familiar with pip and if you can specifiy old versions.

**Comment by habamax** [comment]
As this is not a priority as far as I can see... Does anyone have hack ttfs with slashed 0? Or dotted 0?

Love this font and hate zero it has :)

**Comment by chrissimpkins** [comment]
Not that it is not a priority.  It's just that there are unfortunately others that are higher on the list... Sorry for the delay.

I will build new sets based on the current work in the `dev` branch with slashed and dotted zeroes, then push here over the weekend.  This will provide me with an opportunity to review the build process and troubleshoot the issue here.  It is likely to be a simple glyph name renaming issue in the ttfautohint control instructions files but I need to review the fonts to see what names we need to use as replacements for the `uniXXXX` names in the files that are causing problems.

**Comment by habamax** [comment]
Thx a lot, will wait for slashed one!

**Comment by chrissimpkins** [comment]
These were the type of changes that were required to build with the ttfautohint control instruction files:

![p8axa-image](https://user-images.githubusercontent.com/4249591/54889036-ab63d780-4e78-11e9-8d15-d6455a3ed3c6.png)

Conversion from the Unicode hexadecimal production names (`uniXXXX`) to the name of the glyph in the Basic Latin set does the trick and the build completes to the font files for me.

Note that when you build with alternates for the zero glyph, you need to remove (or comment out) the zero definition lines in each of the four control instructions files on the path `postbuild_processing/tt-hinting/*.txt`.

Swapping out source files now and will push the slash zero and dotted zero builds.

**Comment by chrissimpkins** [comment]
Slashed zero ttf builds based on `dev` branch at https://github.com/source-foundry/Hack/commit/db2d3feb771762953d571cfd3c2b76499f26c23d with current master versions of the alt-hack forward slash zeroes (https://github.com/source-foundry/alt-hack/tree/master/glyphs/u0030-forwardslash)


[ttf.zip](https://github.com/source-foundry/Hack/files/3001150/ttf.zip)

**Comment by chrissimpkins** [comment]
Dotted zero ttf builds based on `dev` branch at https://github.com/source-foundry/Hack/commit/db2d3feb771762953d571cfd3c2b76499f26c23d with current master versions of the alt-hack dotted zeroes (https://github.com/source-foundry/alt-hack/tree/master/glyphs/u0030-dotted)

[ttf.zip](https://github.com/source-foundry/Hack/files/3001170/ttf.zip)

**Comment by chrissimpkins** [comment]
The modifications in the ttfautohint control instructions files were pushed to the `dev` branch and you should be able to build without these errors now.  Please let me know if this did not fix your build issues here.

Thanks much for this report!

**Comment by habamax** [comment]
Thank you! Slashed zero FTW!

**Comment by chrissimpkins** [comment]
@habamax enjoy!
