### ISSUE TITLE
Full matching subscript/superscript digits

### ISSUE THREAD

**Issue by thenlich** [source-foundry/Hack#53]
It would be nice to have a full set of superscript and subscript (dropped below the baseline) digits and other symbols from U+207x and U+208x available, heavily used in math/chem formulas.

The superscript plus (U+207A) and superscript minus U+207B should be raised to match the superscript digits.

**Comment by chrissimpkins** [comment]
Thanks for this information Thomas.  I would definitely like to support mathematics/science uses.  I have the superscript/subscript/scientific inferior numeral glyphs in the set but I need to do a bit of work with them.  I just took a look at the remainder of the Unicode range that you suggested and this will not be difficult to include.  

For my own knowledge and preparation as we begin to support glyphs intended for the sciences/mathematics, can you suggest a good set of editors that are widely used in these fields so that I can test the respective glyphs?

**Comment by thenlich** [comment]
I am talking about programming, so any editor (e.g. Emacs or Notepad++) should do.
In addition to the above, a matching Decimal Exponent Symbol U+23E8 would also be useful.
For good legibility, all glyphs should probably be no smaller than 75% height of full-size (and not have too much spacing either left and right, consider multi-digit numbers)

Here is a quick design sketch of my ideas.
![mono-sub-superscripts](https://cloud.githubusercontent.com/assets/13075200/9610016/2fd73d84-50d7-11e5-9784-c914f6b81a54.png)

**Comment by chrissimpkins** [comment]
That is very helpful.  Thank you very much for adding the mockup.  Does the vertical compression of the glyphs look 'correct' to you for these characters?  It will be a bit of a balancing act between a vertically condensed appearance and too much spacing between glyphs.

**Comment by thenlich** [comment]
The vertical compression looks absolutely right to me, and I think it is also the best thing to do for a monospaced font. It helps to make the super-/subscripts visually distinct from regular digits while still keeping them legible (especially at smaller resolutions).

**Comment by chrissimpkins** [comment]
That is useful to know.  The current glyphs look smaller than this and will need a redesign.  I do intend to include these and will update here when available.

**Comment by chrissimpkins** [comment]
If this is still of interest, perhaps I can put you in touch with @yashevde to discuss?  See his IR #326 

We are willing to support math/sci glyphs but will need feedback from use case experts in these areas.  Let us know if this is of any interest.
